---
name: Go Checks

on:
  push:
    paths:
      - 'apps/**/*.go'
      - 'apps/**/go.mod'
      - '.github/workflows/go-checks.yaml'
      - '.mise.toml'
      - 'Taskfile.yaml'
  pull_request:
    paths:
      - 'apps/**/*.go'
      - 'apps/**/go.mod'
      - '.github/workflows/go-checks.yaml'
      - '.mise.toml'
      - 'Taskfile.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  qbittorrent-natpmp-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
        with:
          version: 2026.9.9
          install_args: go task go:golang.org/x/tools/cmd/goimports
      - run: task go:check
